http:
  port: 8080
admin:
  port: 9876
  hostname: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  api2:
    host: localhost
    paths: '/'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  myservice:
    url: 'http://localhost:8841'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  - name: custom
    apiEndpoints:
      - api2
    policies:
      - key-auth:
      - proxy:
          - action:
              serviceEndpoint: myservice 
              changeOrigin: true
  - name: default
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
